import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

export type SpikeVerdict = "CLEAR" | "PROCEED-WITH-CHANGES" | "BLOCKER" | "INCONCLUSIVE";

export interface SpikeMarkdownReportInput {
  spikeId: string;
  title: string;
  dateLabel: string;
  triggeredBy: string;
  blocks: string;
  verdict: SpikeVerdict;
  question: string;
  method: string;
  evidence: string;
  findings: string;
  implementationRecommendation: string;
  risksAndGaps: string;
}

export interface SpikeReportWriteOptions {
  enabled: boolean;
  explicitPath: string | null;
  defaultFileName: string;
}

export function writeSpikeMarkdownReport(
  input: SpikeMarkdownReportInput,
  options: SpikeReportWriteOptions,
): string | null {
  if (!options.enabled) return null;
  const outputPath = resolve(
    options.explicitPath ?? `docs/plans/spikes/${options.defaultFileName}`,
  );
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${renderSpikeMarkdownReport(input)}\n`, "utf8");
  return outputPath;
}

export function renderSpikeMarkdownReport(input: SpikeMarkdownReportInput): string {
  return `# ${input.spikeId} - ${input.title}

| Field | Value |
|---|---|
| **Spike ID** | ${input.spikeId} |
| **Date** | ${input.dateLabel} |
| **Author** | AI agent (Codex) |
| **Time box** | Live run dependent; report generated by spike probe |
| **Triggered by** | ${input.triggeredBy} |
| **Blocks** | ${input.blocks} |
| **Verdict** | ${input.verdict} |

## Question

${input.question}

## Method

${input.method}

## Evidence

${input.evidence}

## Findings

${input.findings}

## Implementation recommendation

${input.implementationRecommendation}

## Risks / gaps surfaced

${input.risksAndGaps}`;
}

export function fencedJson(value: unknown): string {
  const json = JSON.stringify(value, null, 2).replaceAll("```", "`\\`\\`");
  return `\`\`\`json\n${json}\n\`\`\``;
}

export function recallSpikeTimestamp(now = new Date()): {
  fileTimestamp: string;
  dateLabel: string;
} {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Kolkata",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  })
    .formatToParts(now)
    .reduce<Record<string, string>>((acc, part) => {
      if (part.type !== "literal") acc[part.type] = part.value;
      return acc;
    }, {});

  const date = `${parts.year}-${parts.month}-${parts.day}`;
  const time = `${parts.hour}-${parts.minute}-${parts.second}`;
  return {
    fileTimestamp: `${date}_${time}_IST`,
    dateLabel: `${date} ${parts.hour}:${parts.minute} IST`,
  };
}
